[build]
publish = "build/"
functions = "src/api"

[[redirects]]
from = "/*"
to = "/.netlify/functions/:splat"
status = 200

[functions]
node_bundler = "esbuild"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"